framework:
    cache:
        app: cache.pool.database
        pools:
            cache.pool.database:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.filesystem
