services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $baseDir: "%sigwin_yassg.base_dir%"
            $buildDir: "%sigwin_yassg.build_dir%"
            $routes: "%sigwin_yassg.routes%"

    Sigwin\YASSG\:
        resource: '../src/'
        exclude:
            - '../src/Bridge/Symfony/Serializer/*'
            - '../src/Database/*'
            - '../src/DatabaseProvider.php'
            - '../src/Kernel.php'

    Sigwin\YASSG\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller'
        tags: [ 'controller.service_arguments' ]
    Sigwin\YASSG\Bridge\Symfony\Command\InitCommand:
        $initDir: "%kernel.project_dir%/resources/init"

    sigwin_yassg.abstract.database.storage.filesystem_storage_type:
        class: Sigwin\YASSG\Storage\FilesystemStorage
        tags:
            -
                name: sigwin_yassg.database.storage.type
                type: filesystem
    sigwin_yassg.abstract.database.storage.memory_storage_type:
        class: Sigwin\YASSG\Storage\MemoryStorage
        tags:
            -
                name: sigwin_yassg.database.storage.type
                type: memory

    Sigwin\YASSG\DatabaseProvider:
        arguments:
            $locator: !tagged_locator { tag: 'sigwin_yassg.database', index_by: 'name' }

    sigwin_yassg.expression_language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
        calls:
            -
                registerProvider: [ '@Sigwin\YASSG\Bridge\Symfony\ExpressionLanguage\FunctionProvider' ]

    Sigwin\YASSG\Permutator:
        $expressionLanguage: '@sigwin_yassg.expression_language'

    sigwin_yassg.serializer.denormalizer.localizing:
        class: Sigwin\YASSG\Bridge\Symfony\Serializer\Normalizer\LocalizingNormalizer
        tags:
            -
                name: serializer.normalizer
                priority: 3000
    sigwin_yassg.serializer.denormalizer.collection:
        class: Sigwin\YASSG\Bridge\Symfony\Serializer\Normalizer\CollectionNormalizer
        arguments:
            $expressionLanguage: '@sigwin_yassg.expression_language'
        tags:
            -
                name: serializer.normalizer
                priority: 5000
    sigwin_yassg.serializer.denormalizer.expression:
        class: Sigwin\YASSG\Bridge\Symfony\Serializer\Normalizer\ExpressionNormalizer
        arguments:
            $expressionLanguage: '@sigwin_yassg.expression_language'
        tags:
            -
                name: serializer.normalizer
                priority: 4000
    sigwin_yassg.serializer.denormalizer.locator:
        class: Sigwin\YASSG\Bridge\Symfony\Serializer\Normalizer\ResourceLocatorNormalizer
        arguments:
            $locator: '@file_locator'
        tags:
            -
                name: serializer.normalizer
                priority: 3000

    sigwin_yassg.fragment.renderer.inline:
        class: Sigwin\YASSG\Bridge\Symfony\HttpKernel\Fragment\RelativeUrlInlineFragmentRenderer
        decorates: fragment.renderer.inline

    sigwin_yassg.file_decoder.caching_file_decoder:
        class: Sigwin\YASSG\Decoder\CachingFileDecoder
        decorates: 'Sigwin\YASSG\FileDecoder'

    Sigwin\YASSG\FileDecoder:
        class: Sigwin\YASSG\Decoder\CompositeFileDecoder
        arguments:
            $decoders: !tagged { tag: 'sigwin_yassg.file_decoder' }

    sigwin_yassg.file_decoder.yaml_file_decoder:
        class: Sigwin\YASSG\Decoder\YamlFileDecoder
        tags:
            -
                name: sigwin_yassg.file_decoder

    Symfony\Component\Config\FileLocatorInterface: '@file_locator'

when@prod:
    services:
        Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator:
            decorates: Symfony\Component\Routing\Generator\UrlGeneratorInterface
            arguments:
                $stripParameters: '%sigwin_yassg.routes.strip_parameters%'
                $urlGenerator: '@Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator.inner'
                $routes: "%sigwin_yassg.routes%"

        twig.extension.routing:
            class: Symfony\Bridge\Twig\Extension\RoutingExtension
            arguments:
                $generator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
