services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $data: "%sigwin_yassg.database%"
            $routes: "%sigwin_yassg.routes%"

    Sigwin\YASSG\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Sigwin\YASSG\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller'
        tags: ['controller.service_arguments']
    
when@prod:
    services:
        Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator:
            decorates: Symfony\Component\Routing\Generator\UrlGeneratorInterface
            arguments:
                $urlGenerator: '@Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator.inner'
            
        twig.extension.routing:
            class: Symfony\Bridge\Twig\Extension\RoutingExtension
            arguments:
                $generator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
