services:
    _defaults:
        autowire: true
        autoconfigure: true

    Sigwin\YASSG\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Sigwin\YASSG\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller'
        tags: ['controller.service_arguments']
