services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $data: "%sigwin_yassg.database%"
            $routes: "%sigwin_yassg.routes%"

    Sigwin\YASSG\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Sigwin\YASSG\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller'
        tags: ['controller.service_arguments']
