services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $baseDir: "%sigwin_yassg.base_dir%"
            $buildDir: "%sigwin_yassg.build_dir%"
            $routes: "%sigwin_yassg.routes%"

    Sigwin\YASSG\:
        resource: '../src/'
        exclude:
            - '../src/Database/*'
            - '../src/Kernel.php'

    Sigwin\YASSG\Bridge\Symfony\Controller\:
        resource: '../src/Bridge/Symfony/Controller'
        tags: ['controller.service_arguments']
    Sigwin\YASSG\Bridge\Symfony\Command\InitCommand:
        $initDir: "%kernel.project_dir%/resources/init"
        
    sigwin_yassg.abstract.database.storage.filesystem_storage_type:
        class: Sigwin\YASSG\Storage\FilesystemStorage
        tags:
            - name: sigwin_yassg.database.storage.type
              type: filesystem
    sigwin_yassg.abstract.database.storage.memory_storage_type:
        class: Sigwin\YASSG\Storage\MemoryStorage
        tags:
            - name: sigwin_yassg.database.storage.type
              type: memory

    sigwin_yassg.expression_language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
        calls:
            - registerProvider: ['@Sigwin\YASSG\Bridge\Symfony\ExpressionLanguage\FunctionProvider']
        
    Sigwin\YASSG\Permutator:
        $expressionLanguage: '@sigwin_yassg.expression_language'         

when@prod:
    services:
        Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator:
            decorates: Symfony\Component\Routing\Generator\UrlGeneratorInterface
            arguments:
                $urlGenerator: '@Sigwin\YASSG\Bridge\Symfony\Routing\Generator\FilenameUrlGenerator.inner'

        router.request_context:
            class: Symfony\Component\Routing\RequestContext
            factory: ['@Sigwin\YASSG\Bridge\Symfony\Routing\BuildRequestContextFactory', 'create']
            shared: false

        twig.extension.routing:
            class: Symfony\Bridge\Twig\Extension\RoutingExtension
            arguments:
                $generator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
