name: Build
on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    MutationTest:
        runs-on: ubuntu-latest
        env:
            PHP_VERSION: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "8.0", "8.1", "8.2" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: "actions/checkout@v3"
            -
                name: "Composer install: ${{ matrix.dependencies }}"
                run: make composer/install-${{ matrix.dependencies }}
            -
                name: Tests with mutation
                run: make test
    CodeQualityAnalysis:
        runs-on: ubuntu-latest
        env:
            PHP_VERSION: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "8.0", "8.1", "8.2" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: "actions/checkout@v3"
            -
                name: "Composer install: ${{ matrix.dependencies }}"
                run: make composer/install-${{ matrix.dependencies }}
            -
                name: Run code quality analysis
                run: make analyze
    FunctionalSiteTest:
        runs-on: ubuntu-latest
        steps:
            -
                uses: "actions/checkout@v3"
            -
                name: Composer install
                run: make composer/install
            -
                name: Run build
                working-directory: tests/functional/site
                run: make self/build
            -
                name: Test build
                working-directory: tests/functional/site
                run: make self/test
            -
                name: Link Checker
                uses: lycheeverse/lychee-action@v1.2.0
                with:
                    fail: true
                    args: --verbose --offline --base ./tests/functional/site/public "./tests/functional/site/public/*.html" "./tests/functional/site/public/**/*.html"
    FunctionalInitTest:
        runs-on: ubuntu-latest
        steps:
            -
                uses: "actions/checkout@v3"
            -
                name: Composer install
                run: make composer/install
            -
                name: Run init
                working-directory: tests/functional/init
                run: make -f ../default.mk self/init
            -
                name: Run build
                working-directory: tests/functional/init
                run: make self/build
            -
                name: Test build
                working-directory: tests/functional/init
                run: make self/test
            -
                name: Link Checker
                uses: lycheeverse/lychee-action@v1.2.0
                with:
                    fail: true
                    args: --verbose --offline --base ./tests/functional/init/public "./tests/functional/init/public/*.html" "./tests/functional/init/public/**/*.html"
