name: Build
on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    CodeQualityAnalysis:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install dependencies
                run: make composer-install
            -
                name: Run code quality analysis
                run: make check
    DocumentationQualityAnalysis:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v1
            -
                name: Run documentation quality analysis
                run: make docs

