name: Build
on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    MutationTest:
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "8.0" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install lowest dependencies
                if: "matrix.dependencies == 'lowest'"
                run: make composer-install-lowest
            -
                name: Composer install highest dependencies
                if: "matrix.dependencies == 'highest'"
                run: make composer-install
            -
                name: Tests with mutation
                run: make test
    CodeQualityAnalysis:
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ matrix.php }}
        strategy:
            matrix:
                php: [ "8.0" ]
                dependencies: [ lowest, highest ]
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install lowest dependencies
                if: "matrix.dependencies == 'lowest'"
                run: make composer-install-lowest
            -
                name: Composer install highest dependencies
                if: "matrix.dependencies == 'highest'"
                run: make composer-install
            -
                name: Run code quality analysis
                run: make check
    FunctionalInitTest:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@master
            -
                name: Composer install dependencies
                run: make composer-install
            -
                name: Run init
                working-directory: tests/functional/init
                run: make -f vendor/sigwin/yassg/resources/Makefile self/init
            -
                name: Run build
                working-directory: tests/functional/init
                run: make self/build
            -
                name: Link Checker
                uses: lycheeverse/lychee-action@master
                with:
                    fail: true
                    output: "-"
                    args: --verbose --offline --base ./tests/functional/init/public ./tests/functional/init/public
    DocumentationQualityAnalysis:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v1
            -
                name: Run documentation quality analysis
                run: make docs

